### PR TITLE
Feature/mock api

### PR DESCRIPTION
**Pull request by fran-costa**
Pull request for issue #2

### CODE REVIEW

**Comment by chiiph** [comment]
I really like the way you use some, filter, map, etc. and while it doesn't matter for this specific piece of code, I was wondering why you didn't use dictionaries instead of arrays. Everything in this has a clear key that maps to a unique value (username->account data, username+date->text, token->username).

You don't necessarily need to change anything, but I wanted to start a conversation about it.

**Comment by fran-costa** [comment]
@chiiph, @ivanalejandro0 marked me this yesterday. Next time I will take care about this, but now, as you suggest, I won't change it because for the mock is just for the mock

**Comment by leanbalma** [comment]
This looks great! Good work using those arrays' methods!

I would define the mock using an object tho. Something like:

```javascript
const api = {
  _db: [],
  _privateFunction1() {},
  _privateFunction2() {},
  clearDatabase() {
    this._db = [];
  },
}

export default api;
```

Then, when you want to use it:

```javascript
import api from './api';

api.clearDatabase();
```

That way, private functions and variables get wrapped by your API definition. You export your whole API just once and you can use it as a module.

I'm not encourage you to change it, this is more like a personal preference that I just wanted to share. Again, this looks good to me as it is.

**Comment by ivanalejandro0** [comment]
Note that a function like this:

```js
export function getPref(token, delay = 1000) {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      const userId = getUserIdFromToken(token);
      (userId === null) ?
        reject(new ErrorInvalidToken()) :
        resolve({
          preferences: getUserPreferences(userId)
        });
    }, delay);
  })
}
```

Can be written like this:
```js
function wait(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

export async function getPref(token, delay = 1000) {
  await wait(delay);
  const userId = getUserIdFromToken(token);
  if (userId === null) {
    throw new ErrorInvalidToken();
  }
  return {
    preferences: getUserPreferences(userId)
  }
}
```

Which is more readable, IMO.

**Comment by fran-costa** [comment]
Thanks for the suggestions @chiiph! They are great and clear too =)

I want to ask you about a doubt here: because of the tests, I need functions like initializeMockDatabase() which only have sence in a development environment. I think it would be great to have these functions excluded from the production environment; Is there any right way for doing this?

**Comment by chiiph** [comment]
> I want to ask you about a doubt here: because of the tests, I need functions like initializeMockDatabase() which only have sence in a development environment. I think it would be great to have these functions excluded from the production environment; Is there any right way for doing this?

Well... it depends, you can simply call the methods to add those users and so on as part of the test.

A dirtier approach would be to simply assign to db in the test. @ivanalejandro0 or @leanbalma what's the JS way here?

The resulting code shouldn't have this kind of methods by any means.

**Comment by ivanalejandro0** [comment]
This was a great exercise and served us well while we didn't have a server.
I'm closing this PR since it's no use for us now.

**Pull request closed without merging**
